// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJKVSUlCMUJ1hnLTYE-ZQ5x43odPVEERs',
    appId: '1:1091734607402:web:fe73808fd928f3a36f1553',
    messagingSenderId: '1091734607402',
    projectId: 'splitmate-956d6',
    authDomain: 'splitmate-956d6.firebaseapp.com',
    storageBucket: 'splitmate-956d6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqnK3wr1Q-F-Z12Vi6CAIUKkdaYwP9CDE',
    appId: '1:1091734607402:android:22641bacae67bbc76f1553',
    messagingSenderId: '1091734607402',
    projectId: 'splitmate-956d6',
    storageBucket: 'splitmate-956d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZO2Ltm_PxD2EuEckYy1WdAtkD-y1p3Dk',
    appId: '1:1091734607402:ios:6baf9a59413d10d16f1553',
    messagingSenderId: '1091734607402',
    projectId: 'splitmate-956d6',
    storageBucket: 'splitmate-956d6.appspot.com',
    iosBundleId: 'com.example.splitmateBetaFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZO2Ltm_PxD2EuEckYy1WdAtkD-y1p3Dk',
    appId: '1:1091734607402:ios:6baf9a59413d10d16f1553',
    messagingSenderId: '1091734607402',
    projectId: 'splitmate-956d6',
    storageBucket: 'splitmate-956d6.appspot.com',
    iosBundleId: 'com.example.splitmateBetaFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJKVSUlCMUJ1hnLTYE-ZQ5x43odPVEERs',
    appId: '1:1091734607402:web:f18589fa455abcdc6f1553',
    messagingSenderId: '1091734607402',
    projectId: 'splitmate-956d6',
    authDomain: 'splitmate-956d6.firebaseapp.com',
    storageBucket: 'splitmate-956d6.appspot.com',
  );
}
